"""phases 4-10: pages words/image, doc_type nullable, splitting, suppliers

Revision ID: 28c0cd721077
Revises: 8080a492c046
Create Date: 2026-09-27 12:07:10.965877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28c0cd721077'
down_revision: Union[str, None] = '8080a492c046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_supplier_tenant_name')
    )
    op.create_index(op.f('ix_suppliers_tenant_id'), 'suppliers', ['tenant_id'], unique=False)
    op.add_column('documents', sa.Column('split_from_document_id', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('page_start', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('page_end', sa.Integer(), nullable=True))
    op.alter_column('documents', 'doc_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'documents', 'documents', ['split_from_document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.alter_column('documents', 'doc_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('documents', 'page_end')
    op.drop_column('documents', 'page_start')
    op.drop_column('documents', 'split_from_document_id')
    op.drop_index(op.f('ix_suppliers_tenant_id'), table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
